var fs = require("fs");
var fp = "C:\\Users\\huang\\Desktop\\workspace\\SOP\\012-个人博客网站\\wrangler.toml";
var c = [
  "[vars]",
  'NEXT_PUBLIC_SITE_URL = "https://your-domain.pages.dev"',
  "",
  "[build]",
  'command = "npm run build"',
  'output_dir = ".next"',
  "",
  "[[rules]]",
  'glob = "**/*"',
  'type = "ESModule"',
  'skip_processing = true',
  "",
  "[[rules]]",
  'glob = "*.html"',
  'type = "Assets"',
  'skip_processing = false',
  "",
  "[[rules]]",
  'glob = "*.js"',
  'type = "JavaScript"',
  'skip_processing = false',
  "",
  "[[rules]]",
  'glob = "*.css"',
  'type = "Css"',
  'skip_processing = false',
  "",
  "[[rules]]",
  'glob = "*.json"',
  'type = "Data"',
  'skip_processing = true',
  "",
  "[[rules]]",
  'glob = "*.{png,jpg,gif,svg,webp,ico}"',
  'type = "Media"',
  'skip_processing = true',
  "",
  "[[rules]]",
  'glob = "*.woff2"',
  'type = "Media"',
  'skip_processing = true',
].join("\n");
fs.writeFileSync(fp, c, "utf8");
console.log("Updated wrangler.toml");